# Prometheus Configuration v2.40.0
# Main configuration file for Bookman AI platform monitoring

# Global configuration
global:
  scrape_interval: 15s      # Default scrape interval for all jobs
  evaluation_interval: 15s   # Interval for evaluating rules
  scrape_timeout: 10s       # Timeout for scrape requests
  external_labels:
    environment: production
    region: global
    platform: bookman-ai

# Rule files to load
rule_files:
  - "rules/alerts.yml"      # Service and resource alerting rules
  - "rules/recording.yml"   # Performance and utilization recording rules

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
      scheme: https
      tls_config:
        cert_file: /etc/prometheus/certs/alertmanager.crt
        key_file: /etc/prometheus/certs/alertmanager.key
      timeout: 5s
      api_version: v2

# Storage configuration
storage:
  tsdb:
    retention_time: 15d     # Data retention period
    retention_size: 50GB    # Maximum storage size
    wal_compression: true   # Enable WAL compression
    min_block_duration: 2h
    max_block_duration: 24h

# Scrape configurations
scrape_configs:
  # API Gateway monitoring
  - job_name: api-gateway
    metrics_path: /metrics
    scheme: https
    tls_config:
      cert_file: /etc/prometheus/certs/api-gateway.crt
      key_file: /etc/prometheus/certs/api-gateway.key
    static_configs:
      - targets: ['api-gateway:9090']
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: api-gateway

  # Authentication Service monitoring
  - job_name: auth-service
    metrics_path: /metrics
    scheme: https
    tls_config:
      cert_file: /etc/prometheus/certs/auth-service.crt
      key_file: /etc/prometheus/certs/auth-service.key
    static_configs:
      - targets: ['auth-service:9090']
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: auth-service

  # Education Service monitoring
  - job_name: education-service
    metrics_path: /metrics
    scheme: https
    tls_config:
      cert_file: /etc/prometheus/certs/education-service.crt
      key_file: /etc/prometheus/certs/education-service.key
    static_configs:
      - targets: ['education-service:9090']
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: education-service

  # Market Analysis Service monitoring
  - job_name: market-analysis
    metrics_path: /metrics
    scheme: https
    tls_config:
      cert_file: /etc/prometheus/certs/market-analysis.crt
      key_file: /etc/prometheus/certs/market-analysis.key
    static_configs:
      - targets: ['market-analysis:9090']
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: market-analysis

  # Portfolio Service monitoring
  - job_name: portfolio-service
    metrics_path: /metrics
    scheme: https
    tls_config:
      cert_file: /etc/prometheus/certs/portfolio-service.crt
      key_file: /etc/prometheus/certs/portfolio-service.key
    static_configs:
      - targets: ['portfolio-service:9090']
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: portfolio-service

  # Security Service monitoring
  - job_name: security-service
    metrics_path: /metrics
    scheme: https
    tls_config:
      cert_file: /etc/prometheus/certs/security-service.crt
      key_file: /etc/prometheus/certs/security-service.key
    static_configs:
      - targets: ['security-service:9090']
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: security-service

  # Node Exporter for host metrics
  - job_name: node-exporter
    metrics_path: /metrics
    scheme: https
    tls_config:
      cert_file: /etc/prometheus/certs/node-exporter.crt
      key_file: /etc/prometheus/certs/node-exporter.key
    static_configs:
      - targets: ['node-exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: ${1}

  # Kubernetes service discovery
  - job_name: kubernetes-pods
    kubernetes_sd_configs:
      - role: pod
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name

# Remote write configuration for long-term storage
remote_write:
  - url: "https://thanos-receive:19291/api/v1/receive"
    remote_timeout: 30s
    queue_config:
      capacity: 10000
      max_shards: 200
      max_samples_per_send: 500
    tls_config:
      cert_file: /etc/prometheus/certs/remote-write.crt
      key_file: /etc/prometheus/certs/remote-write.key