# Kubernetes Secrets manifest for Bookman AI Platform
# Version: 1.0.0
# Contains sensitive configuration data and credentials for all microservices
# Encryption: AES-256-GCM at rest
# Rotation Schedule: 30 days
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  labels:
    app: bookman-ai
    environment: ${ENVIRONMENT}
    version: 1.0.0
    managed-by: terraform
  annotations:
    secret.version: 1.0.0
    secret.update-time: ${TIMESTAMP}
    secret.rotation-schedule: 30d
    secret.last-rotated: ${LAST_ROTATION_DATE}
    secret.encryption: aes-256-gcm
type: Opaque
data:
  JWT_SECRET: ${JWT_SECRET}
  JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
  OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
  OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
  ADMIN_API_KEY: ${ADMIN_API_KEY}
  DB_PASSWORD: ${AUTH_DB_PASSWORD}
  MFA_ENCRYPTION_KEY: ${MFA_ENCRYPTION_KEY}
  SESSION_ENCRYPTION_KEY: ${SESSION_ENCRYPTION_KEY}
---
apiVersion: v1
kind: Secret
metadata:
  name: market-analysis-secrets
  labels:
    app: bookman-ai
    environment: ${ENVIRONMENT}
    version: 1.0.0
    managed-by: terraform
  annotations:
    secret.version: 1.0.0
    secret.update-time: ${TIMESTAMP}
    secret.rotation-schedule: 30d
    secret.last-rotated: ${LAST_ROTATION_DATE}
    secret.encryption: aes-256-gcm
type: Opaque
data:
  TIMESCALE_USER: ${TIMESCALE_USER}
  TIMESCALE_PASSWORD: ${TIMESCALE_PASSWORD}
  API_KEY_BINANCE: ${BINANCE_API_KEY}
  API_KEY_COINGECKO: ${COINGECKO_API_KEY}
  ML_MODEL_KEY: ${ML_MODEL_KEY}
  DATA_ENCRYPTION_KEY: ${DATA_ENCRYPTION_KEY}
  CACHE_ENCRYPTION_KEY: ${CACHE_ENCRYPTION_KEY}
---
apiVersion: v1
kind: Secret
metadata:
  name: education-service-secrets
  labels:
    app: bookman-ai
    environment: ${ENVIRONMENT}
    version: 1.0.0
    managed-by: terraform
  annotations:
    secret.version: 1.0.0
    secret.update-time: ${TIMESTAMP}
    secret.rotation-schedule: 30d
    secret.last-rotated: ${LAST_ROTATION_DATE}
    secret.encryption: aes-256-gcm
type: Opaque
data:
  DB_PASSWORD: ${EDUCATION_DB_PASSWORD}
  AI_API_KEY: ${AI_API_KEY}
  STORAGE_ACCESS_KEY: ${STORAGE_ACCESS_KEY}
  STORAGE_SECRET_KEY: ${STORAGE_SECRET_KEY}
  CONTENT_ENCRYPTION_KEY: ${CONTENT_ENCRYPTION_KEY}
  USER_DATA_KEY: ${USER_DATA_KEY}
---
apiVersion: v1
kind: Secret
metadata:
  name: portfolio-service-secrets
  labels:
    app: bookman-ai
    environment: ${ENVIRONMENT}
    version: 1.0.0
    managed-by: terraform
  annotations:
    secret.version: 1.0.0
    secret.update-time: ${TIMESTAMP}
    secret.rotation-schedule: 30d
    secret.last-rotated: ${LAST_ROTATION_DATE}
    secret.encryption: aes-256-gcm
type: Opaque
data:
  DB_PASSWORD: ${PORTFOLIO_DB_PASSWORD}
  REDIS_PASSWORD: ${PORTFOLIO_REDIS_PASSWORD}
  ENCRYPTION_KEY: ${PORTFOLIO_ENCRYPTION_KEY}
  WALLET_ENCRYPTION_KEY: ${WALLET_ENCRYPTION_KEY}
  TRANSACTION_KEY: ${TRANSACTION_KEY}
  BACKUP_ENCRYPTION_KEY: ${BACKUP_ENCRYPTION_KEY}
---
apiVersion: v1
kind: Secret
metadata:
  name: security-service-secrets
  labels:
    app: bookman-ai
    environment: ${ENVIRONMENT}
    version: 1.0.0
    managed-by: terraform
  annotations:
    secret.version: 1.0.0
    secret.update-time: ${TIMESTAMP}
    secret.rotation-schedule: 30d
    secret.last-rotated: ${LAST_ROTATION_DATE}
    secret.encryption: aes-256-gcm
type: Opaque
data:
  DB_PASSWORD: ${SECURITY_DB_PASSWORD}
  BLOCKCHAIN_API_KEY: ${BLOCKCHAIN_API_KEY}
  AUDIT_API_KEY: ${AUDIT_API_KEY}
  THREAT_DETECTION_KEY: ${THREAT_DETECTION_KEY}
  ALERT_ENCRYPTION_KEY: ${ALERT_ENCRYPTION_KEY}
  SCANNING_API_KEY: ${SCANNING_API_KEY}
---
apiVersion: v1
kind: Secret
metadata:
  name: community-service-secrets
  labels:
    app: bookman-ai
    environment: ${ENVIRONMENT}
    version: 1.0.0
    managed-by: terraform
  annotations:
    secret.version: 1.0.0
    secret.update-time: ${TIMESTAMP}
    secret.rotation-schedule: 30d
    secret.last-rotated: ${LAST_ROTATION_DATE}
    secret.encryption: aes-256-gcm
type: Opaque
data:
  DB_PASSWORD: ${COMMUNITY_DB_PASSWORD}
  REDIS_PASSWORD: ${COMMUNITY_REDIS_PASSWORD}
  NOTIFICATION_API_KEY: ${NOTIFICATION_API_KEY}
  MESSAGE_ENCRYPTION_KEY: ${MESSAGE_ENCRYPTION_KEY}
  SOCKET_KEY: ${SOCKET_KEY}
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secrets
  labels:
    app: bookman-ai
    environment: ${ENVIRONMENT}
    version: 1.0.0
    managed-by: terraform
  annotations:
    secret.version: 1.0.0
    secret.update-time: ${TIMESTAMP}
    secret.rotation-schedule: 30d
    secret.last-rotated: ${LAST_ROTATION_DATE}
    secret.encryption: aes-256-gcm
type: kubernetes.io/tls
data:
  tls.crt: ${TLS_CERTIFICATE}
  tls.key: ${TLS_PRIVATE_KEY}
  ca.crt: ${CA_CERTIFICATE}