# Elasticsearch 8.0+ Configuration for Bookman AI Platform
# Purpose: Centralized logging system configuration with enhanced security and performance settings

#----------------------
# Cluster Configuration
#----------------------
cluster.name: bookman-elasticsearch
cluster.initial_master_nodes: ["${HOSTNAME}"]
discovery.seed_hosts: ["elasticsearch-master"]
cluster.routing.allocation.disk.threshold_enabled: true
cluster.routing.allocation.disk.watermark.low: "85%"
cluster.routing.allocation.disk.watermark.high: "90%"
cluster.routing.allocation.awareness.attributes: zone
cluster.routing.allocation.enable: all
cluster.max_shards_per_node: 2000

#----------------------
# Node Configuration
#----------------------
node.name: "${HOSTNAME}"
node.master: true
node.data: true
node.ingest: true
node.max_local_storage_nodes: 1
node.processors: 4
node.attr.zone: "${ZONE}"
node.store.allow_mmap: false

#----------------------
# Network Configuration
#----------------------
network.host: "0.0.0.0"
http.port: 9200
transport.port: 9300
http.cors.enabled: true
http.cors.allow-origin: "*"
http.max_content_length: "100mb"
http.compression: true
http.compression_level: 3
transport.tcp.compress: true

#----------------------
# Security Configuration
#----------------------
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.keystore.path: elastic-certificates.p12
xpack.security.audit.enabled: true
xpack.security.audit.logfile.events.include: 
  - authentication_success
  - authentication_failure
  - access_denied
  - connection_denied
xpack.license.self_generated.type: basic
xpack.monitoring.enabled: true
xpack.monitoring.collection.enabled: true

#----------------------
# Memory & JVM Settings
#----------------------
bootstrap.memory_lock: true
indices.memory.index_buffer_size: "30%"
indices.queries.cache.size: "5%"
indices.fielddata.cache.size: "20%"
indices.breaker.total.use_real_memory: true
indices.breaker.fielddata.limit: "40%"
indices.breaker.request.limit: "30%"

#----------------------
# Path Configuration
#----------------------
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs
path.repo: ["/usr/share/elasticsearch/snapshots"]
path.shared_data: /usr/share/elasticsearch/shared

#----------------------
# Index Configuration
#----------------------
action.auto_create_index: ".monitoring-*,.watches,.triggered_watches,.watcher-history-*,.ml-*"
action.destructive_requires_name: true
indices.recovery.max_bytes_per_sec: "40mb"
indices.lifecycle.history_index_enabled: true
indices.lifecycle.poll_interval: "10m"
indices.recovery.max_concurrent_file_chunks: 5

#----------------------
# Thread Pool Settings
#----------------------
thread_pool.write.size: 4
thread_pool.write.queue_size: 1000
thread_pool.search.size: 8
thread_pool.search.queue_size: 2000
thread_pool.get.size: 4
thread_pool.get.queue_size: 1000
thread_pool.analyze.size: 2
thread_pool.analyze.queue_size: 500