# Loki Configuration v2.8.0
# Centralized logging configuration for Bookman AI platform

# Server configuration
server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s
  grpc_server_max_recv_msg_size: 67108864  # 64MB
  log_level: info
  http_server_idle_timeout: 120s

# Common configuration shared across components
common:
  path_prefix: /loki
  replication_factor: 3
  ring:
    kvstore:
      store: memberlist
      prefix: collectors/
    heartbeat_timeout: 1m
    instance_interface_names:
      - eth0
      - en0

# Storage configuration with S3 backend
storage_config:
  aws:
    s3:
      bucket_name: bookman-logs
      region: us-west-2
      endpoint: s3.amazonaws.com
      insecure: false
      sse_encryption: true
      http_config:
        idle_conn_timeout: 90s
        response_header_timeout: 30s
        insecure_skip_verify: false
      s3forcepathstyle: false
      access_key_id: ${AWS_ACCESS_KEY_ID}
      secret_access_key: ${AWS_SECRET_ACCESS_KEY}

  # Local storage for index and cache
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    cache_ttl: 24h
    shared_store: s3
    resync_interval: 5m
    mode: read-write

  # Schema configuration for log storage
  schema_config:
    configs:
      - from: "2023-01-01"
        store: boltdb-shipper
        object_store: aws
        schema: v12
        index:
          prefix: index_
          period: 24h
          tags:
            service: bookman
            environment: ${ENVIRONMENT}

# Ingester configuration for log processing
ingester:
  lifecycler:
    ring:
      replication_factor: 3
      kvstore:
        store: memberlist
    final_sleep: 0s
    heartbeat_period: 5s
    join_after: 30s
    min_ready_duration: 1m
    interface_names:
      - eth0
      - en0
  chunk_idle_period: 1h
  chunk_block_size: 262144  # 256KB
  chunk_retain_period: 1m
  max_transfer_retries: 0
  wal:
    enabled: true
    dir: /loki/wal
    replay_memory_ceiling: 512MB
    flush_on_shutdown: true

# Query configuration
querier:
  engine:
    timeout: 3m
    max_look_back_period: 720h  # 30 days
  query_ingesters_within: 3h
  query_store_after: 12h
  max_concurrent: 16
  query_timeout: 1m

# Query frontend configuration
frontend:
  compress_responses: true
  log_queries_longer_than: 10s
  downstream_url: http://querier:3100
  max_outstanding_per_tenant: 2048

# Limits configuration
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h  # 7 days
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  max_entries_limit_per_query: 5000
  max_query_length: 721h  # 30 days + 1 hour buffer
  max_query_parallelism: 32
  cardinality_limit: 100000
  per_stream_rate_limit: 5MB
  per_stream_rate_limit_burst: 10MB

# Table manager for retention and cleanup
table_manager:
  retention_deletes_enabled: true
  retention_period: 168h  # 7 days
  poll_interval: 10m
  creation_grace_period: 10m

# Compactor configuration
compactor:
  working_directory: /loki/compactor
  shared_store: s3
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  compaction_window: 1h
  max_compaction_parallelism: 10

# Memberlist configuration for clustering
memberlist:
  join_members:
    - loki-memberlist
  dead_node_reclaim_time: 30s
  gossip_interval: 5s
  gossip_nodes: 3
  retransmit_factor: 2
  bind_port: 7946
  bind_addr: 0.0.0.0

# Runtime configuration
runtime_config:
  file: /etc/loki/runtime.yaml
  reload_period: 10s

# Analytics configuration
analytics:
  reporting_enabled: false